#!/usr/bin/env bash
# Fizzbuzz

counter=1

while [ $counter -lt 101 ];
do
    if [ $((counter%15)) = 0 ];
    then
        echo "FizzBuzz"
    elif [ $((counter%5)) = 0 ];
    then
        echo "Buzz"
    elif [ $((counter%3)) = 0 ];
    then
        echo "Fizz"
    else
        echo "$counter"
    fi
    counter=$((counter + 1))
done
